version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: php-apache
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/.htaccess:/var/www/html/.htaccess
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: granja-serra-dourada
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
